jobs:
- template: .ci/build.yaml  # Template reference
  parameters:
    host: macOS
    pool:
      vmImage: 'macOS-latest'

- template: .ci/build.yaml  # Template reference
  parameters:
    host: Linux
    pool:
      vmImage: 'ubuntu-latest'

- template: .ci/build.yaml  # Template reference
  parameters:
    host: Windows
    pool:
      vmImage: 'windows-latest'
    sign: true  # Extra step on Windows only
